title: "Viktor Plattner"
description: "Neuroscientist • Data/Systems • Lab Infrastructure"
theme: minimal-mistakes-jekyll
# theme: jekyll-theme-primer
markdown: kramdown
author:
  name: "Viktor Plattner"
