# ===========================================
# SITE CONFIGURATION
# ===========================================

# Site identity
title: "Viktor Plattner"                    # Site title (appears in header)
description: "Neuroscientist • Data/Systems • Lab Infrastructure"  # Site description
# url: "https://viktorpm.github.io"         # Your site URL (uncomment if needed)
# baseurl: ""                               # Subdirectory path (if any)

# ===========================================
# TECHNICAL SETTINGS
# ===========================================

# Core Jekyll settings
theme: jekyll-theme-cayman                  # Theme name
markdown: kramdown                          # Markdown processor
highlighter: rouge                          # Code syntax highlighting
# permalink: pretty                         # URL structure (pretty, date, etc.)
# timezone: "Europe/London"                 # Site timezone
# lang: "en"                                # Site language

# ===========================================
# CONTACT & SOCIAL
# ===========================================

# Contact information
# email: "v.plattner@ucl.ac.uk"             # Your email address
# github_username: "viktorpm"               # GitHub username
# twitter_username: "your-twitter"         # Twitter handle
# linkedin_username: "your-linkedin"       # LinkedIn username


# ===========================================
# PLUGINS & EXTENSIONS
# ===========================================

# Jekyll plugins (GitHub Pages compatible)
plugins:
  - jekyll-feed                             # RSS feed generation
  - jekyll-sitemap                          # Sitemap generation
  - jekyll-seo-tag                          # SEO meta tags
  # - jekyll-optional-front-matter          # Optional front matter
  # - jekyll-readme-index                   # README as index page
  # - jekyll-default-layout                # Default layouts
  # - jekyll-titles-from-headings           # Auto-generate titles

# ===========================================
# THEME CUSTOMIZATION
# ===========================================

# Cayman theme options
# show_excerpts: true                       # Show post excerpts on home page
# show_post_footer: true                    # Show post footers with date/tags

# ===========================================
# ANALYTICS & SEO
# ===========================================

# Analytics
# google_analytics: "G-XXXXXXXXXX"          # Google Analytics ID
# google_site_verification: "verification_code"  # Google Search Console

# SEO settings
# twitter:
#   username: "your-twitter"                # Twitter username for SEO
#   card: "summary"                         # Twitter card type

# ===========================================
# CONTENT SETTINGS
# ===========================================

# Collections (custom content types)
# collections:
#   projects:
#     output: true
#     permalink: /:collection/:name/
#   talks:
#     output: true
#     permalink: /:collection/:name/

# Pagination
# paginate: 5                                # Posts per page
# paginate_path: "/page:num/"               # Pagination URL structure

# ===========================================
# NAVIGATION
# ===========================================

# Site navigation
# navigation:
#   - title: "Home"
#     url: "/"
#   - title: "About"
#     url: "/about"
#   - title: "Projects"
#     url: "/projects"

# ===========================================
# BUILD SETTINGS
# ===========================================

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md
  - scripts/
  # - _drafts/                               # Draft posts
  # - _posts/                               # Post files (if not using)

# Include files in build
# include:
#   - _pages/                               # Custom pages directory
#   - _data/                                # Data files directory

# ===========================================
# ADVANCED OPTIONS
# ===========================================

# Jekyll processing
# incremental: true                         # Incremental builds
# future: false                             # Show future-dated posts
# limit_posts: 0                           # Limit number of posts
# keep_files: []                           # Files to keep during clean

# Liquid processing
# liquid:
#   error_mode: warn                        # Liquid error handling
#   strict_filters: false                   # Strict filter mode
#   strict_variables: false                 # Strict variable mode
